#! /bin/bash
# https://stackoverflow.com/questions/29142/getting-ssh-to-execute-a-command-in-the-background-on-target-machine

EC2_HOSTS=(
    ec2-34-238-192-84.compute-1.amazonaws.com
    ec2-13-231-206-182.ap-northeast-1.compute.amazonaws.com
    ec2-13-239-22-118.ap-southeast-2.compute.amazonaws.com
    ec2-34-248-209-79.eu-west-1.compute.amazonaws.com
    ec2-18-231-122-62.sa-east-1.compute.amazonaws.com
    ec2-3-101-37-125.us-west-1.compute.amazonaws.com
)

DNS_SERVER="cs5700cdnproject.ccs.neu.edu"

while [[ $# -gt 1 ]]
do
    key="$1"
    case $key in
        -p)
        PORT="$2"
        shift
        ;;
        -o)
        ORIGIN="$2"
        shift
        ;;
        -n)
        NAME="$2"
        shift
        ;;
        -u)
        USERNAME="$2"
        shift
        ;;
        -i)
        KEYFILE="$2"
        shift
        ;;
        *)
        ;;
    esac
    shift
done

echo "run httpserver"
for HOST in "${EC2_HOSTS[@]}"
do
    echo "$HOST"
    ssh -i $KEYFILE -n -f $USERNAME@$HOST "sh -c 'cd ~/cdnproject/; nohup ./httpserver -p $PORT -o $ORIGIN  &'"
done

echo "run dnsserver"
echo "$DNS_SERVER"
    ssh -i $KEYFILE -n -f $USERNAME@$DNS_SERVER "sh -c 'cd ~/cdnproject/; nohup ./dnsserver -p $PORT -n $NAME > /dev/null 2>&1 &'"