#! /bin/bash
EC2_HOSTS=(
    ec2-34-238-192-84.compute-1.amazonaws.com
    ec2-13-231-206-182.ap-northeast-1.compute.amazonaws.com
    ec2-13-239-22-118.ap-southeast-2.compute.amazonaws.com
    ec2-34-248-209-79.eu-west-1.compute.amazonaws.com
    ec2-18-231-122-62.sa-east-1.compute.amazonaws.com
    ec2-3-101-37-125.us-west-1.compute.amazonaws.com
)

DNS_SERVER="cs5700cdnproject.ccs.neu.edu"

while [[ $# -gt 1 ]]
do
    key="$1"
    case $key in
        -p)
        PORT="$2"
        echo "$PORT"
        shift
        ;;
        -o)
        ORIGIN="$2"
        echo "$ORIGIN"
        shift
        ;;
        -n)
        NAME="$2"
        echo "$NAME"
        shift
        ;;
        -u)
        USERNAME="$2"
        echo "$USERNAME"
        shift
        ;;
        -i)
        KEYFILE="$2"
        echo "$KEYFILE"
        shift
        ;;
        *)
        ;;
    esac
    shift
done

echo "stop http server"
for HOST in "${EC2_HOSTS[@]}"
do
    echo "$HOST"
    ssh -i $KEYFILE $USERNAME@$HOST "killall python > /dev/null 2>&1"
done

echo "stop dns server"
    ssh -i $KEYFILE $USERNAME@$DNS_SERVER "killall python > /dev/null 2>&1"